//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0-b52-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.12.03 at 01:58:12 PM EST 
//


package com.ensense.insense.core.analytics.model;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for HarReports element declaration.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;element name="HarReports">
 *   &lt;complexType>
 *     &lt;complexContent>
 *       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *         &lt;sequence>
 *           &lt;element name="ApplicationName" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *           &lt;element name="startdate" type="{http://www.w3.org/2001/XMLSchema}dateTime"/>
 *           &lt;element name="PageDetail" maxOccurs="unbounded" minOccurs="0">
 *             &lt;complexType>
 *               &lt;complexContent>
 *                 &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                   &lt;sequence>
 *                     &lt;element name="PageTitle" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                     &lt;element name="PageName" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                     &lt;element name="Url" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                     &lt;element name="TagUrl" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                     &lt;element name="RefererUrl" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                     &lt;element name="TagType" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                     &lt;element name="tagData" maxOccurs="unbounded" minOccurs="0">
 *                       &lt;complexType>
 *                         &lt;complexContent>
 *                           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                             &lt;sequence>
 *                               &lt;element name="tagName" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                               &lt;element name="tagValue" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                             &lt;/sequence>
 *                           &lt;/restriction>
 *                         &lt;/complexContent>
 *                       &lt;/complexType>
 *                     &lt;/element>
 *                   &lt;/sequence>
 *                 &lt;/restriction>
 *               &lt;/complexContent>
 *             &lt;/complexType>
 *           &lt;/element>
 *         &lt;/sequence>
 *       &lt;/restriction>
 *     &lt;/complexContent>
 *   &lt;/complexType>
 * &lt;/element>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "applicationName",
    "startdate",
    "pageDetail"
})
@XmlRootElement(name = "HarReports")
public class HarReports {

    @XmlElement(name = "ApplicationName", required = true)
    protected String applicationName;
    @XmlElement(required = true)
    protected XMLGregorianCalendar startdate;
    @XmlElement(name = "PageDetail", required = true)
    protected List<PageDetail> pageDetail;

    /**
     * Gets the value of the applicationName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getApplicationName() {
        return applicationName;
    }

    /**
     * Sets the value of the applicationName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setApplicationName(String value) {
        this.applicationName = value;
    }

    /**
     * Gets the value of the startdate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getStartdate() {
        return startdate;
    }

    /**
     * Sets the value of the startdate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setStartdate(XMLGregorianCalendar value) {
        this.startdate = value;
    }

    /**
     * Gets the value of the pageDetail property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the pageDetail property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getPageDetail().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link PageDetail }
     * 
     * 
     */
    public List<PageDetail> getPageDetail() {
        if (pageDetail == null) {
            pageDetail = new ArrayList<PageDetail>();
        }
        return this.pageDetail;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="PageTitle" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="PageName" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="Url" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="TagUrl" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="RefererUrl" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="TagType" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="tagData" maxOccurs="unbounded" minOccurs="0">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="tagName" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *                   &lt;element name="tagValue" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "pageTitle",
        "pageName",
        "url",
        "tagUrl",
        "refererUrl",
        "tagType",
        "tagData"
    })
    public static class PageDetail {

        @XmlElement(name = "PageTitle", required = true)
        protected String pageTitle;
        @XmlElement(name = "PageName", required = true)
        protected String pageName;
        @XmlElement(name = "Url", required = true)
        protected String url;
        @XmlElement(name = "TagUrl", required = true)
        protected String tagUrl;
        @XmlElement(name = "RefererUrl", required = true)
        protected String refererUrl;
        @XmlElement(name = "TagType", required = true)
        protected String tagType;
        @XmlElement(required = true)
        protected List<TagData> tagData;

        /**
         * Gets the value of the pageTitle property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getPageTitle() {
            return pageTitle;
        }

        /**
         * Sets the value of the pageTitle property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setPageTitle(String value) {
            this.pageTitle = value;
        }

        /**
         * Gets the value of the pageName property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getPageName() {
            return pageName;
        }

        /**
         * Sets the value of the pageName property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setPageName(String value) {
            this.pageName = value;
        }

        /**
         * Gets the value of the url property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getUrl() {
            return url;
        }

        /**
         * Sets the value of the url property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setUrl(String value) {
            this.url = value;
        }

        /**
         * Gets the value of the tagUrl property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getTagUrl() {
            return tagUrl;
        }

        /**
         * Sets the value of the tagUrl property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setTagUrl(String value) {
            this.tagUrl = value;
        }

        /**
         * Gets the value of the refererUrl property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getRefererUrl() {
            return refererUrl;
        }

        /**
         * Sets the value of the refererUrl property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setRefererUrl(String value) {
            this.refererUrl = value;
        }

        /**
         * Gets the value of the tagType property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getTagType() {
            return tagType;
        }

        /**
         * Sets the value of the tagType property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setTagType(String value) {
            this.tagType = value;
        }

        /**
         * Gets the value of the tagData property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the tagData property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getTagData().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link TagData }
         * 
         * 
         */
        public List<TagData> getTagData() {
            if (tagData == null) {
                tagData = new ArrayList<TagData>();
            }
            return this.tagData;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="tagName" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
         *         &lt;element name="tagValue" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "tagName",
            "tagValue"
        })
        public static class TagData {

            protected String tagName;
            protected String tagValue;

            /**
             * Gets the value of the tagName property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getTagName() {
                return tagName;
            }

            /**
             * Sets the value of the tagName property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setTagName(String value) {
                this.tagName = value;
            }

            /**
             * Gets the value of the tagValue property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getTagValue() {
                return tagValue;
            }

            /**
             * Sets the value of the tagValue property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setTagValue(String value) {
                this.tagValue = value;
            }

        }

    }

}
