//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0-b52-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.07.21 at 12:10:33 PM EDT 
//


package com.ensense.insense.core.transaction.model.jaxb;

import javax.xml.bind.annotation.*;
import java.util.ArrayList;
import java.util.List;


/**
 * <p>Java class for LinkNavigation element declaration.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;element name="LinkNavigation">
 *   &lt;complexType>
 *     &lt;complexContent>
 *       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *         &lt;sequence>
 *           &lt;element name="NavigationDetails" maxOccurs="unbounded" minOccurs="0">
 *             &lt;complexType>
 *               &lt;complexContent>
 *                 &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                   &lt;sequence>
 *                     &lt;element name="linkTitle" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                     &lt;element name="NavigationPath" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                     &lt;element name="pageTitle" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                     &lt;element name="href" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                     &lt;element name="transactionExists" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *                     &lt;element name="Accessibility" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *                     &lt;element name="errorPage" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *                      &lt;element name="parentUrl" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *                   &lt;/sequence>
 *                 &lt;/restriction>
 *               &lt;/complexContent>
 *             &lt;/complexType>
 *           &lt;/element>
 *         &lt;/sequence>
 *       &lt;/restriction>
 *     &lt;/complexContent>
 *   &lt;/complexType>
 * &lt;/element>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "navigationDetails"
})
@XmlRootElement(name = "LinkNavigation")
public class LinkNavigation {

    @XmlElement(name = "NavigationDetails", required = true)
    protected List<NavigationDetails> navigationDetails;

    /**
     * Gets the value of the navigationDetails property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the navigationDetails property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getNavigationDetails().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link NavigationDetails }
     * 
     * 
     */
    public List<NavigationDetails> getNavigationDetails() {
        if (navigationDetails == null) {
            navigationDetails = new ArrayList<NavigationDetails>();
        }
        return this.navigationDetails;
    }


    @Override
	public String toString() {
		return "LinkNavigation [navigationDetails=" + navigationDetails + "]";
	}


	/**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="linkTitle" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="NavigationPath" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="pageTitle" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="href" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="transactionExists" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
     *         &lt;element name="Accessibility" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
     *         &lt;element name="Errorpage" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
     *         &lt;element name="parentUrl" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "linkTitle",
        "navigationPath",
        "pageTitle",
        "href",
        "transactionExists",
        "accessibility",
        "errorPage",
        "parentUrl",
        "noOfOldTiaaImage",
        "noOfNewTiaaImage",
        "noOfOldTiaaUrl",
        "noOfNewTiaaUrl",
        "noOfOldTiaaContent",
        "noOfNewTiaaContent"
    })
    public static class NavigationDetails {

        @XmlElement(required = true)
        protected String linkTitle;
        @XmlElement(name = "NavigationPath", required = true)
        protected String navigationPath;
        @XmlElement(required = true)
        protected String pageTitle;
        @XmlElement(required = true)
        protected String href;
        protected boolean transactionExists;
        @XmlElement(name = "Accessibility")
        protected boolean accessibility;
        @XmlElement(name = "ErrorPage")
        protected boolean errorPage;
        @XmlElement(name = "parentUrl")
        protected String parentUrl;
        @XmlElement(name = "noOfOldTiaaImage")
        int noOfOldTiaaImage;
        @XmlElement(name = "noOfNewTiaaImage")
        int noOfNewTiaaImage;
        @XmlElement(name = "noOfOldTiaaUrl")
        int noOfOldTiaaUrl;
        @XmlElement(name = "noOfNewTiaaUrl")
        int noOfNewTiaaUrl;
        @XmlElement(name = "noOfOldTiaaContent")
        int noOfOldTiaaContent;
        @XmlElement(name = "noOfNewTiaaContent")
        int noOfNewTiaaContent;
        
        /**
         * Gets the value of the linkTitle property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getLinkTitle() {
            return linkTitle;
        }

        /**
         * Sets the value of the linkTitle property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setLinkTitle(String value) {
            this.linkTitle = value;
        }

        /**
         * Gets the value of the navigationPath property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getNavigationPath() {
            return navigationPath;
        }

        /**
         * Sets the value of the navigationPath property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setNavigationPath(String value) {
            this.navigationPath = value;
        }

        /**
         * Gets the value of the pageTitle property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getPageTitle() {
            return pageTitle;
        }

        /**
         * Sets the value of the pageTitle property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setPageTitle(String value) {
            this.pageTitle = value;
        }

        /**
         * Gets the value of the href property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getHref() {
            return href;
        }

        /**
         * Sets the value of the href property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setHref(String value) {
            this.href = value;
        }

        /**
         * Gets the value of the transactionExists property.
         * 
         */
        public boolean isTransactionExists() {
            return transactionExists;
        }

        /**
         * Sets the value of the transactionExists property.
         * 
         */
        public void setTransactionExists(boolean value) {
            this.transactionExists = value;
        }

        /**
         * Gets the value of the accessibility property.
         * 
         */
        public boolean isAccessibility() {
            return accessibility;
        }

        /**
         * Sets the value of the errorPage property.
         * 
         */
        public void setErrorPage(boolean value) {
            this.errorPage = value;
        }

        /**
         * Gets the value of the errorPage property.
         * 
         */
        public boolean isErrorPage() {
            return errorPage;
        }

        /**
         * Sets the value of the accessibility property.
         * 
         */
        public void setAccessibility(boolean value) {
            this.accessibility = value;
        }
        
		public String getParentUrl() {
			return parentUrl;
		}

		public void setParentUrl(String parentUrl) {
			this.parentUrl = parentUrl;
		}

		public int getNoOfOldTiaaImage() {
			return noOfOldTiaaImage;
		}

		public void setNoOfOldTiaaImage(int noOfOldTiaaImage) {
			this.noOfOldTiaaImage = noOfOldTiaaImage;
		}

		public int getNoOfNewTiaaImage() {
			return noOfNewTiaaImage;
		}

		public void setNoOfNewTiaaImage(int noOfNewTiaaImage) {
			this.noOfNewTiaaImage = noOfNewTiaaImage;
		}

		public int getNoOfOldTiaaUrl() {
			return noOfOldTiaaUrl;
		}

		public void setNoOfOldTiaaUrl(int noOfOldTiaaUrl) {
			this.noOfOldTiaaUrl = noOfOldTiaaUrl;
		}

		public int getNoOfNewTiaaUrl() {
			return noOfNewTiaaUrl;
		}

		public void setNoOfNewTiaaUrl(int noOfNewTiaaUrl) {
			this.noOfNewTiaaUrl = noOfNewTiaaUrl;
		}

		public int getNoOfOldTiaaContent() {
			return noOfOldTiaaContent;
		}

		public void setNoOfOldTiaaContent(int noOfOldTiaaContent) {
			this.noOfOldTiaaContent = noOfOldTiaaContent;
		}

		public int getNoOfNewTiaaContent() {
			return noOfNewTiaaContent;
		}

		public void setNoOfNewTiaaContent(int noOfNewTiaaContent) {
			this.noOfNewTiaaContent = noOfNewTiaaContent;
		}

		@Override
		public String toString() {
			return "NavigationDetails [linkTitle=" + linkTitle
					+ ", navigationPath=" + navigationPath + ", pageTitle="
					+ pageTitle + ", href=" + href + ", transactionExists="
					+ transactionExists + ", accessibility=" + accessibility
					+ ", errorPage=" + errorPage + ", parentUrl=" + parentUrl
					+ ", noOfOldTiaaImage=" + noOfOldTiaaImage
					+ ", noOfNewTiaaImage=" + noOfNewTiaaImage
					+ ", noOfOldTiaaUrl=" + noOfOldTiaaUrl
					+ ", noOfNewTiaaUrl=" + noOfNewTiaaUrl
					+ ", noOfOldTiaaContent=" + noOfOldTiaaContent
					+ ", noOfNewTiaaContent=" + noOfNewTiaaContent + "]";
		}

    }

}
