//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0-b52-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.07.21 at 12:10:33 PM EDT 
//


package com.ensense.insense.core.transaction.model.jaxb;

import javax.xml.bind.annotation.XmlRegistry;
import com.cts.mint.transaction.model.jaxb.LinkNavigation.NavigationDetails;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.cts.mint.transaction.model.jaxb package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.cts.mint.transaction.model.jaxb
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link NavigationDetails }
     * 
     */
    public NavigationDetails createLinkNavigationNavigationDetails() {
        return new NavigationDetails();
    }

    /**
     * Create an instance of {@link LinkNavigation }
     * 
     */
    public LinkNavigation createLinkNavigation() {
        return new LinkNavigation();
    }

}
